# Generated by Django 4.0.5 on 2022-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Professor', 'Professor'), ('Businessman', 'Businessman'), ('Sciencist', 'Sciencist'), ('Farmer', 'Farmer'), ('NGO', 'NGO'), ('Banker', 'Banker'), ('Others', 'Others')], max_length=100)),
                ('mother_occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Professor', 'Professor'), ('Businessman', 'Businessman'), ('Sciencist', 'Sciencist'), ('Housewife', 'Housewife'), ('NGO', 'NGO'), ('Banker', 'Banker'), ('Others', 'Others')], max_length=100)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('gernder', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Others', 'Others')], max_length=10)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christan', 'Chirstan'), ('Hindu', 'Hindu'), ('Buddho', 'Buddho'), ('Others', 'Others')], max_length=50)),
                ('profile_img', models.ImageField(upload_to='assets/images')),
            ],
        ),
    ]
