# Generated by Django 4.0.5 on 2022-07-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentForm',
            new_name='Student',
        ),
    ]
